// JavaScript Document
function addtofav(){ 
	var title = document.title;
	var url = document.location.href;
	if (document.all) 
		window.external.AddFavorite(url, title); 
	else if (window.sidebar) 
		window.sidebar.addPanel(title, url, "");
}

function showMark (){
	document.getElementById("markbox").style.display="block";
}

function hideMark(){
	document.getElementById("markbox").style.display = "none";
}

document.writeln("<li><img src=\"http:\/\/static.shihui.cn\/images\/mark\/myfav.gif\" border=\"0\" align=\"absmiddle\"\/><a href=\"javascript:;\" onClick=\"addtofav()\" title=\"添加到收藏夹\">本地收藏夹<\/a><\/li>");
document.writeln("<li><img title=\"添加到QQ书签\" src=\"http:\/\/static.shihui.cn\/images\/mark\/qq.gif\" align=\"absmiddle\" border=\"0\" \/><a href=\"javascript:window.open(\'http:\/\/shuqian.qq.com\/post?from=3&amp;title=\'+encodeURIComponent(document.title)+\'&amp;uri=\'+encodeURIComponent(document.location.href)+\'&amp;jumpback=2&amp;noui=1\',\'favit\',\'\');void(0)\">QQ书签<\/a><\/li>");
document.writeln("<li><img src=\"http:\/\/static.shihui.cn\/images\/mark\/baidu.gif\" border=\"0\" title=\"添加到百度搜藏\" align=\"absmiddle\" \/><a href=\"javascript:u=location.href;t=document.title;c = %22%22 + (window.getSelection ? window.getSelection() : document.getSelection ? document.getSelection() : document.selection.createRange().text);var url=%22http:\/\/cang.baidu.com\/do\/add?it=%22+encodeURIComponent(t)+%22&amp;iu=%22+encodeURIComponent(u)+%22&amp;dc=%22+encodeURIComponent(c)+%22&amp;fr=ien#nw=1%22;window.open(url,%22_blank%22,%22scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes%22); void(0)\">百度搜藏<\/a><\/li>");
document.writeln("<li><img src=\"http:\/\/static.shihui.cn\/images\/mark\/google.gif\" border=\"0\" align=\"absmiddle\" \/><a href=\"javascript:u=location.href;t=document.title;var url=\'http:\/\/www.google.com\/bookmarks\/mark?op=add&amp;bkmk=\'+encodeURIComponent(u)+\'&amp;title=\'+encodeURIComponent(t);window.open(url,%22_blank%22,%22scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes%22); void(0)\" title=\"添加到google收藏\">Google收藏<\/a><\/li>");
document.writeln("<li><img src=\"http:\/\/static.shihui.cn\/images\/mark\/vivi.gif\" align=\"absmiddle\" border=\"0\" \/><a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(vivi=window.open(\'http:\/\/vivi.sina.com.cn\/collect\/icollect.php?pid=xuxule.net&amp;title=\'+escape(d.title)+\'&amp;url=\'+escape(d.location.href)+\'&amp;desc=\'+escape(t),\'vivi\',\'scrollbars=no,width=480,height=480,left=75,top=20,status=no,resizable=yes\'));vivi.focus();\" title=\"添加到新浪ViVi\">新浪ViVi<\/a><\/li>");
document.writeln("<li><img src=\"http:\/\/static.shihui.cn\/images\/mark\/yahoo.gif\" border=\"0\" align=\"absmiddle\" \/><a href=\"javascript: var url=\'http:\/\/myweb.cn.yahoo.com\/popadd.html?url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title);window.open(url,%22_blank%22,%22scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes%22); void(0);\" title=\"添加到雅虎收藏夹\">雅虎收藏夹<\/a><\/li>");
document.writeln("<li><img title=\"添加到我摘\" src=\"http:\/\/static.shihui.cn\/images\/mark\/wozhai.gif\" align=\"absmiddle\" border=\"0\" \/><a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(wozhai=window.open(\'http:\/\/www.wozhai.com\/wozhai\/Cento.asp#t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t),\'wozhai\',\'scrollbars=no,width=475,height=575,left=75,top=20,status=no,resizable=yes\'));wozhai.focus();\">我摘<\/a><\/li>");
document.writeln("<li><img title=\"添加到Digbuzz我挖网\" src=\"http:\/\/static.shihui.cn\/images\/mark\/digbuzz.gif\" align=\"absmiddle\" border=\"0\" \/><a href=\"javascript:q=(document.location.href);void(open(\'http:\/\/www.digbuzz.org\/submit.php?url=\'+encodeURIComponent(q),\'\',\'\'));\">Digbuzz我挖网<\/a><\/li>");
document.writeln("<li><img title=\"添加到POCO网摘\" src=\"http:\/\/static.shihui.cn\/images\/mark\/poco.gif\" align=\"absmiddle\" border=\"0\" \/><a");
document.writeln("href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange");
document.writeln("().text:\'\'):(d.getSelection?d.getSelection():\'\');void(vivi=window.open(\'http:\/\/my.poco.cn\/fav\/storeIt.php?t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t),\'_blank\',\'scrollbars=no,width=475,height=575,left=75,top=20,status=no,resizable=yes\'));\" title=\"收藏到POCO网摘\">POCO网摘<\/a><\/li>");
document.writeln("<li><img title=\"添加到diigo\" src=\"http:\/\/static.shihui.cn\/images\/mark\/diglog.JPG\" align=\"absmiddle\" border=\"0\" \/><a title=\"推荐到diglog\" href=\"javascript:\/\/\" onclick=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(keyit=window.open(\'http:\/\/www.diglog.com\/submit.aspx?title=\'+escape(d.title)+\'&url=\'+escape(d.location.href)+\'&description=\'+escape(t),\'keyit\',\'resizable,location,menubar,toolbar,scrollbars,status\'));keyit.focus();\">奇客diglog<\/a><\/li>");
document.writeln("<li><img title=\"添加到抓虾\" src=\"http:\/\/static.shihui.cn\/images\/mark\/welcome_logo.gif\" align=\"absmiddle\" border=\"0\" \/> <a target=_blank href=\"http:\/\/www.zhuaxia.com\/add_channel.php?sourceid=102&url=\">抓虾<\/a><\/li>");
document.writeln("<li><img title=\"添加到diigo\" src=\"http:\/\/static.shihui.cn\/images\/mark\/365key.gif\" align=\"absmiddle\" border=\"0\" \/><a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(keyit=window.open(\'http:\/\/www.365key.com\/storeit.aspx?t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t),\'keyit\',\'scrollbars=no,width=475,height=575,left=75,top=20,status=no,resizable=yes\'));keyit.focus();\" title=\"功能强大的网络收藏夹，一秒钟操作就可以轻松实现保存带来的价值、分享带来的快乐\">365Key<\/a><\/li>");
document.writeln("<li><img title=\"添加到鲜果\" src=\"http:\/\/static.shihui.cn\/images\/mark\/xianguo.gif\" align=\"absmiddle\" border=\"0\" \/><a target=\"_blank\" href=\"http:\/\/www.xianguo.com\/subscribe.php?url=www.shihui.cn\">鲜果<\/a><\/li>");
document.writeln("<li><img title=\"添加到饭否\" src=\"http:\/\/static.shihui.cn\/images\/mark\/fan.gif\" align=\"absmiddle\" border=\"0\" \/><a target=\"_blank\" href=\"http:\/\/www.xianguo.com\/subscribe.php?url=www.shihui.cn\">饭否<\/a><\/li>");
document.writeln("<li><img title=\"添加天极网摘\" src=\"http:\/\/static.shihui.cn\/images\/mark\/yesky.gif\" align=\"absmiddle\" border=\"0\" \/><a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(yesky=window.open(\'http:\/\/hot.yesky.com\/dp.aspx?t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t)+\'&st=2\',\'_blank\',\'scrollbars=no,width=400,height=480,left=75,top=20,status=no,resizable=yes\'));yesky.focus();\"title=\"推荐到天极网摘\">天极网摘<\/a><\/li>");
document.writeln("<li><img title=\"添加到和讯网摘\" src=\"http:\/\/static.shihui.cn\/images\/mark\/hexun.gif\" align=\"absmiddle\" border=\"0\" \/><a href=\"javascript:t=document.title;u=location.href;e=document.selection?(document.selection.type!=\'None\'?document.selection.createRange().text:\'\'):(document.getSelection?document.getSelection():\'\');void(open(\'http:\/\/bookmark.hexun.com\/post.aspx?title=\'+escape(t)+\'&url=\'+escape(u)+\'&excerpt=\'+escape(e),\'HexunBookmark\',\'scrollbars=no,width=600,height=450,left=80,top=80,status=no,resizable=yes\'));\">和讯网摘<\/a><\/li>");